name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps

    - name: Build React app
      run: |
        npm run build:client
        echo "Build completed successfully"
      env:
        NODE_ENV: production

    - name: Prepare for GitHub Pages
      run: |
        echo "=== Checking build output ==="
        ls -la dist/public/
        
        # Ensure 404.html exists for SPA routing
        if [ ! -f dist/public/404.html ]; then
          echo "Creating 404.html for SPA routing"
          cat > dist/public/404.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>Property Management Pulse</title>
          <script>
            var pathSegmentsToKeep = 1;
            var l = window.location;
            l.replace(
              l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
              l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
              l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
              (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
              l.hash
            );
          </script>
        </head>
        <body></body>
        </html>
        EOF
        fi
        
        echo "=== Final files ==="
        find dist/public -name "*.html" -o -name "*.js" -o -name "*.css" | head -10

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
